name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy.yml'
      - 'infra/Dockerfile'
      - 'agent/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ACA_RESOURCE_GROUP: ${{ vars.ACA_RESOURCE_GROUP }}
      ACA_ENVIRONMENT: ${{ vars.ACA_ENVIRONMENT }}
      ACA_APP_NAME: ${{ vars.ACA_APP_NAME }}
      ACA_REGION: ${{ vars.ACA_REGION }}
      IMAGE: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

      - name: Azure CLI - deploy to Container Apps
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az extension add -n containerapp --yes
            az containerapp up \
              --name "$ACA_APP_NAME" \
              --resource-group "$ACA_RESOURCE_GROUP" \
              --environment "$ACA_ENVIRONMENT" \
              --image "$IMAGE" \
              --ingress external --target-port 8000 \
              --location "$ACA_REGION" \
              --env-vars \
                GRAPH_TENANT_ID=secretref:GRAPH_TENANT_ID \
                GRAPH_CLIENT_ID=secretref:GRAPH_CLIENT_ID \
                GRAPH_CLIENT_SECRET=secretref:GRAPH_CLIENT_SECRET \
                GRAPH_SCOPES="Calendars.ReadWrite Mail.ReadWrite Mail.Send User.Read Files.ReadWrite offline_access" \
                ANTHROPIC_API_KEY=secretref:ANTHROPIC_API_KEY \
                TEAMS_WEBHOOK_URL=secretref:TEAMS_WEBHOOK_URL \
                AZURE_SPEECH_KEY=secretref:AZURE_SPEECH_KEY \
                AZURE_SPEECH_REGION=westeurope \
                VOICE_TTS_VOICE=de-DE-KatjaNeural
